version: "3.4"
services:
 music_player:
   image: node:alpine
   container_name: musicplayer
   entrypoint: /bin/sh
   ports:
     - 8080:8080
   working_dir: /src/app
   volumes:
   
     - type: bind
       source: ./
       target: /src/app
   tty: true